system_settings:
  model_id: anthropic.claude-3-sonnet-20240229-v1:0
  region_name: us-east-1
  embedding_model_id: amazon.titan-embed-text-v2:0
  collection_name: markdown_header_level2_1024split_64overlap
  search_kwargs:
    k: 10


user_settings:
  models: 
    - anthropic.claude-3-sonnet-20240229-v1:0
    - anthropic.claude-3-haiku-20240307-v1:0
    - meta.llama3-70b-instruct-v1:0
  top_k:
    min: 1
    max : 10
    default: 4
  
  response_length:
    - short
    - medium
    - long
