[theme]
base="light"
primaryColor="#96bfff" # used by certain widgets
backgroundColor="#FFFFFF" # used by the main app background
secondaryBackgroundColor="#d9e6fa" # used by the sidebar background and for most interactive widgets
textColor="#31333F" # used by the main text color
font="serif"

[client]
showSidebarNavigation = false

[server]
headless = true